// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izedteuzpeekjxkswfwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6ZWR0ZXV6cGVla2p4a3N3ZndnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDk2MTgsImV4cCI6MjA2ODkyNTYxOH0.N87zUQEfTTXmuIJv9sXTYgvnaWUiajU6RVKVWFiumEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});